# main settings file for the game / engine

[gun]

[gun.transform]
positionX = 10
positionY = 5
positionZ = 0

[gun.model]
modelPath = "Resources/Geometry/Guns/AK/AK.obj"
moldeMaterial = "Resources/textures/GunAK.mtl"

[gun.specifics]
gunName = "AK"
magCount = 5
magSize = 30
fireRate = 0.2

# used for defining the mag as a child object
[gun.mag]
hasChild = true
childName = "AKmagazine"
childPath = "Resources/Geometry/Guns/AK/magazineAK.obj"

