# main settings file for the game / engine

[gun]

[gun.transform]
positionX = -2.5
positionY = 5
positionZ = 0

[gun.model]
modelPath = "Resources/Geometry/Guns/Glock/glock.obj"
moldeMaterial = "Resources/Geometry/Guns/Glock/glock.mtl"

[gun.specifics]
gunName = "glock"
magCount = 5
magSize = 19
fireRate = 0.4

# used for defining the mag as a child object
[gun.mag]
hasChild = false
childName = "AKmagazine"
childPath = "Resources/Geometry/Guns/AK/magazineAK.obj"

