# main settings file for the game / engine

[gun]

[gun.transform]
positionX = 2.5
positionY = 5
positionZ = 0

[gun.model]
modelPath = "Resources/Geometry/Guns/RayGun/raygun.obj"
moldeMaterial = "Resources/Geometry/Guns/RayGun/raygun.mtl"

[gun.specifics]
gunName = "raygun"
magCount = 5
magSize = 30
fireRate = 0.2

# used for defining the mag as a child object
[gun.mag]
hasChild = false
childName = "AKmagazine"
childPath = "Resources/Geometry/Guns/AK/magazineAK.obj"

