# main settings file for the game / engine

[settings]

[settings.controls]
move_forward = "W"
move_back = "S"
move_left = "A"
move_right = "D"
# look_left = "q"
# look_right = "e"
# up = "space"
# down = "left_shift"

[settings.display]
resolution = "800x800"
fullscreen = false
vsync = false
fov = 90

[settings.graphics]
texture_quality = "high" # low, medium, high, ultra
shadow_quality = "high"
anti_aliasing = "high"
post_processing = "high"

[settings.audio]
master_volume = 0.5
music_volume = 0.5
effects_volume = 0.5

[settings.gameplay]
mouse_sensitivity = 1.0
difficulty = "normal"
